export const LOAD_CURRENT_WEATHER_REQUEST = 'LOAD_CURRENT_WEATHER_REQUEST';
export const LOAD_CURRENT_WEATHER_SUCCESS = 'LOAD_CURRENT_WEATHER_SUCCESS';
export const LOAD_CURRENT_WEATHER_FAILURE = 'LOAD_CURRENT_WEATHER_FAILURE';

export const LOAD_WEATHER_HISTORY_REQUEST = 'LOAD_WEATHER_HISTORY_REQUEST';
export const LOAD_WEATHER_HISTORY_SUCCESS = 'LOAD_WEATHER_HISTORY_SUCCESS';
export const LOAD_WEATHER_HISTORY_FAILURE = 'LOAD_WEATHER_HISTORY_FAILURE';

export const LOAD_WEATHER_FORECAST_SUCCESS = 'LOAD_WEATHER_FORECAST_SUCCESS';
